### ISSUE TITLE
Zone mean air temperature is weird in Case 600FF and Case 900FF

### ISSUE THREAD

**Issue by YUIWK** [NREL/BESTEST-GSR#6]
Hi, I am a freshman to energy+ and the BESTEST.
I downloaded Case 600FF and Case 900FF and ran them. I didn't change any setting. But the simulation result is quite weird to me. The zone mean air temperature even increases to 60℃ in winter. It seems unreal. Could anyone tell the possible reason? Thank you.
The red line shows the temperature of Case900FF, and the blue line is the temperature of Case600FF.
![airtem Case600FF Case900FF](https://user-images.githubusercontent.com/40563079/70372567-0f093480-1924-11ea-84de-604474e0b7e7.png)

**Comment by mjwitte** [comment]
South facing glass in a lightweight building with no ventilation or HVAC will get very warm in winter.
(In the future, questions like this are more appropriate at unmethours.com). Issue are for defects and new feature requests.

**Comment by YUIWK** [comment]
Thank you for your answer. I'll delete this post and ask it at unmethours.
